### ISSUE TITLE
`copy` does not copy on ArchLinux

### ISSUE THREAD

**Issue by amtoine** [FMotalleb/nu_plugin_clipboard#1]
i was able to make the plugin work on Ubuntu, no issues :ok_hand: 

however, on my ArchLinux personal machine, `clipboard copy` does not appear to be working...

> **Note**
> the following behaviour does not occur when i paste from selecting text in my browser for instance => i can paste it and even use `clipboard paste` without any issues in that case :ok_hand: 
>
> it's really when using `clipboard copy` that `clipboard paste` and the *normal paste* don't work

## repro
```nushell
> "foo" | clipboard copy
foo
```
```nushell
> clipboard paste
Error:   × get clipboard content error
   ╭─[entry #5:1:1]
 1 │ clipboard paste
   · ───────┬───────
   ·        ╰── The clipboard contents were not available in the requested format or the clipboard is empty.
   ╰────
```

and finally using `ctrl + shift + v` in Nushell does not paste either, so it appears the clipboard is indeed empty

**Comment by amtoine** [comment]
| key                | value                                                     |
| ------------------ | --------------------------------------------------------- |
| version            | 0.87.0                                                    |
| branch             |                                                           |
| commit_hash        |                                                           |
| build_os           | linux-x86_64                                              |
| build_target       | x86_64-unknown-linux-gnu                                  |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                       |
| rust_channel       | stable-x86_64-unknown-linux-gnu                           |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                       |
| build_time         | 2023-11-15 18:45:43 +01:00                                |
| build_rust_channel | release                                                   |
| allocator          | mimalloc                                                  |
| features           | default, sqlite, trash, which, zip                        |
| installed_plugins  | clipboard copy, clipboard paste, jwalk, nu_plugin_explore |

**Comment by fmotalleb** [comment]
Hi! can you try `use-wayland` feature?

**Comment by amtoine** [comment]
no luck after
```nushell
cargo build --features use-wayland --release
register target/release/nu_plugin_clipboard
```
:cry: 

i'm using x11
