### ISSUE TITLE
Dependency ahash fails the build

### ISSUE THREAD

**Issue by AceofSpades5757** [FMotalleb/nu_plugin_clipboard#9]
One of your locked dependencies is broken, `ahash`. The issue is fixed using `cargo update --recursive`. PR will be posted shortly.

Here's the forum where the issue and fixes are discussed. https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445

Here's what I get on Windows running `cargo build` or `cargo build --release`:

![image](https://github.com/user-attachments/assets/8bcc8cc6-9484-46dd-b11f-fbe3ff125718)

**Comment by fmotalleb** [comment]
Hi, Tnx for the report. the reason why I did not merge your pr is I already updated `Cargo.toml` because of the Nushell update.
this should be fixed now.

**Comment by AceofSpades5757** [comment]
No problem. As long as the issue is fixed for the next person, I'm happy. Thanks and I appreciate your plugin!
